events {}

http {
    server {
        listen 8080;
        server_name _;

        location /matches/ {
            add_header Access-Control-Allow-Origin "http://localhost:5173" always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

            proxy_pass http://icarus-matches:4002/;
        }

        location /auth/ {
            proxy_pass http://icarus-auth:4001/;
        }

        location /rooms/ {
            proxy_pass http://icarus-rooms:4003/;
        }

        location /analytics/ {
            proxy_pass http://icarus-analytics:4004/;
        }
    }
}