events {}

http {

    server {
        listen 8080;

        location /matches/ {
            proxy_pass http://icarus-matches:4002/;
        }

        location /auth/ {
            proxy_pass http://icarus-auth:4001/;
        }

        location /rooms/ {
            proxy_pass http://icarus-rooms:4003/;
        }

        location /analytics/ {
            proxy_pass http://icarus-analytics:4004/;
        }
    }

}