services:
  gateway:
    build:
      context: ../gateway
    container_name: icarus-gateway
    ports:
      - "8081:8080"
    depends_on:
      - auth-service
      - matches-service
      - rooms-service
      - profile-service
      - analytics-service
      - store-service
      - cards-service
    networks:
      - supabase_net

  auth-service:
    build:
      context: ../services/auth-service
    container_name: icarus-auth
    environment:
      PORT: 4001
      AUTH_DB_URL: postgresql://auth_svc:AuthSvc_2026_dev@supabase-db-do4ksgcc0wksg4wwg4osgk0o:5432/auth_db
      JWT_SECRET: dev_secret
    networks:
      - supabase_net

  matches-service:
    build:
      context: ../services/matches-service
    container_name: icarus-matches
    environment:
      PORT: 4002
      MATCHES_DB_URL: postgresql://matches_svc:MatchesSvc_2026_dev@supabase-db-do4ksgcc0wksg4wwg4osgk0o:5432/matches_db
    networks:
      - supabase_net

  rooms-service:
    build:
      context: ../services/rooms-service
    container_name: icarus-rooms
    environment:
      PORT: 4003
      ROOMS_DB_URL: postgresql://rooms_svc:RoomsSvc_2026_dev@supabase-db-do4ksgcc0wksg4wwg4osgk0o:5432/rooms_db
    networks:
      - supabase_net

  analytics-service:
    build:
      context: ../services/analytics-service
    container_name: icarus-analytics
    environment:
      PORT: 4004
      ANALYTICS_DB_URL: postgresql://analytics_svc:AnalyticsSvc_2026_dev@supabase-db-do4ksgcc0wksg4wwg4osgk0o:5432/analytics_db
    networks:
      - supabase_net

  store-service:
    build:
      context: ../services/store-service
    container_name: icarus-store
    environment:
      PORT: 4005
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - supabase_net

  profile-service:
    build:
      context: ../services/profile-service
    container_name: icarus-profile
    environment:
      PORT: 4006
      PROFILE_DB_URL: postgresql://profile_svc:ProfileSvc_2026_dev@supabase-db:5432/profile_db
    networks:
      - supabase_net

  cards-service:
    build:
      context: ../services/cards-service
    container_name: icarus-cards
    environment:
      PORT: 4009
      CARDS_DB_URL: postgresql://cards_svc:CardsSvc_2026_dev@supabase-db-do4ksgcc0wksg4wwg4osgk0o:5432/cards_db
    networks:
      - supabase_net

networks:
  supabase_net:
    external: true
    name: do4ksgcc0wksg4wwg4osgk0o