services:
  matches-service:
    environment:
      MATCHES_DB_URL: postgresql://matches_svc:MatchesSvc_2026_dev@host.docker.internal:15432/matches_db
      DEMO_MATCH_IDS: "2"

  rooms-service:
    environment:
      ROOMS_DB_URL: postgresql://rooms_svc:RoomsSvc_2026_dev@host.docker.internal:15432/rooms_db
      ROOMS_CHAT_PRUNE_INTERVAL_MS: "120000"

  analytics-service:
    environment:
      ANALYTICS_DB_URL: postgresql://analytics_svc:AnalyticsSvc_2026_dev@host.docker.internal:15432/analytics_db

  profile-service:
    environment:
      PROFILE_DB_URL: postgresql://profile_svc:ProfileSvc_2026_dev@host.docker.internal:15432/profile_db